<?php

declare(strict_types=1);

namespace App\Admin;

use App\Domain\User\Entity\Types\Role;
use App\Domain\User\Entity\Types\Status;
use Knp\Menu\ItemInterface;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Admin\AdminInterface;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class UserAdmin extends AbstractAdmin
{
    protected function configureTabMenu(ItemInterface $menu, $action, ?AdminInterface $childAdmin = null)
    {
        parent::configureTabMenu($menu, $action, $childAdmin); // TODO: Change the autogenerated stub
    }

    protected function configureFormFields(FormMapper $form)
    {
        $form->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('role', ChoiceType::class, [ 'choices' => Role::getAllRoles() ])
            ->add('status', ChoiceType::class, [ 'choices' => Status::getAllStatus() ]);
    }

    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter
            ->add('email');
    }

    protected function configureListFields(ListMapper $list)
    {
        $list->addIdentifier('email')
            ->add('status')
            ->add('role');
    }
}